"""
GTA V English to Indonesian Gaming Glossary & Proper Nouns Registry.
Follows professional gaming localization standards for UI, HUD, missions, and gameplay.
Contains comprehensive terminology for UI, Menus, Heists, Dialogue, Activities, and News.
"""

from typing import Dict, Set, List, Tuple

# Protected proper nouns that should NOT be translated
PROTECTED_PROPER_NOUNS: Set[str] = {
    # Characters
    "Michael", "Trevor", "Franklin", "Lamar", "Lester", "Brad", "Ron", "Wade",
    "Amanda", "Jimmy", "Tracey", "Chop", "Dave Norton", "Steve Haines", "Devin Weston",
    "Wei Cheng", "Stretch", "Solomon Richards", "Molly", "Floyd", "Patricia", "Tanisha",
    "Denise", "Beverly", "Barry", "Mary-Ann", "Dom", "Omega", "Abigail", "Hao", "Maude",
    "Cletus", "Josh", "Nigel", "Mrs. Thornhill", "Dr. Friedlander", "Cris Formage",
    "Martin Madrazo", "Lazlow", "Tony Prince", "English Dave", "Moodymann", "KDJ",
    "Sessanta", "Pavel", "El Rubio", "Agent 14", "Avon Hertz", "Cliffford",
    "Sabrina Gray", "Billy Wiener", "Tao Cheng", "Chef", "Simeon Yetarian", "Jay Norris",

    # Locations & Districts
    "Los Santos", "Blaine County", "San Andreas", "Sandy Shores", "Paleto Bay",
    "Grapeseed", "Vinewood", "Vinewood Hills", "West Vinewood", "Downtown Vinewood",
    "Rockford Hills", "Richman", "Morningwood", "Pacific Bluffs", "Del Perro",
    "Vespucci", "Vespucci Beach", "Vespucci Canals", "La Puerta", "South Los Santos",
    "Davis", "Strawberry", "Chamberlain Hills", "Rancho", "Banning", "Elysian Island",
    "Terminal", "Port of Los Santos", "Los Santos International Airport", "LSIA",
    "Pillbox Hill", "Mission Row", "Textile City", "Legion Square", "Little Seoul",
    "Downtown", "Mirror Park", "East Los Santos", "El Burro Heights", "Murrieta Heights",
    "Cypress Flats", "Tataviam Mountains", "Palomino Highlands", "Tongva Hills",
    "Tongva Valley", "Banham Canyon", "Chumash", "Lago Zancudo", "Fort Zancudo",
    "Mount Josiah", "Mount Chiliad", "Mount Gordo", "Raton Canyon", "Cassidy Creek",
    "Alamo Sea", "Grand Senora Desert", "San Chianski Mountain Range", "Cayo Perico",
    "North Yankton", "Ludendorff",

    # Factions, Agencies & Corporations
    "Rockstar Games", "Rockstar", "GTA Online", "FIB", "IAA", "Merryweather",
    "Merryweather Security", "LSPD", "LSSD", "NOOSE", "Ammu-Nation", "Lifeinvader",
    "Bleeter", "Eyefind", "Maze Bank", "Fleeca", "Fleeca Bank", "Bank of Liberty",
    "Union Depository", "Epsilon", "Epsilon Program", "Children of the Mountain",
    "Altruist Cult", "Lost MC", "The Lost MC", "Vagos", "Los Santos Vagos",
    "Ballas", "Families", "The Families", "Chamberlain Gangster Families", "Kkangpae",
    "Triads", "Los Santos Triads", "Armenian Mob", "Madrazo Cartel", "Marabunta Grande",
    "Humane Labs", "Humane Labs and Research", "Kortz Center", "Richards Majestic",
    "Gruppe Sechs",

    # Vehicle Brands & Models
    "Albany", "Annis", "Benefactor", "BF", "Bravado", "Brute", "Canis", "Cheval",
    "Classique", "Declasse", "Dewbauchee", "Dinka", "Dundreary", "Emperor", "Enus",
    "Fathom", "Gallivanter", "Grotti", "Hijak", "HVY", "Invetero", "JoBuilt",
    "Karin", "Lampadati", "Liberty City Cycles", "LCC", "Maibatsu", "Mammoth",
    "MTL", "Nagasaki", "Obey", "Ocelot", "Overflod", "Pegassi", "Pfister",
    "Principe", "Progen", "Rune", "Schyster", "Shitzu", "Stanley", "Truffade",
    "Ubermacht", "Vapid", "Vulcar", "Weeny", "Western Company", "Western Motorcycle Company",
    "Zirconium", "Buckingham", "Manchez", "Chimera", "Terrorbyte", "Velum", "Scarab",
    "Seashark",

    # In-game Brands, Food & Fictional Goods
    "Sprunk", "eCola", "Pisswasser", "PiSS.WASS.ER", "EgoChaser", "Meteorite",
    "Redwood", "P's & Q's", "Vom Feuer", "Daily Globe", "Los Santos Meteor",
    "Liberty Tree", "WNKA International", "Talkin' Balls", "Los Santos Shepherd",

    # Radios & Media
    "Radio Los Santos", "Space 103.2", "West Coast Classics", "Rebel Radio",
    "Los Santos Rock Radio", "The Lowdown 91.1", "Blue Ark", "Worldwide FM",
    "FlyLo FM", "The Wave 103", "Radio Mirror Park", "Vinewood Boulevard Radio",
    "Soulwax FM", "Non-Stop-Pop FM", "Blaine County Radio", "WCTR", "KULT FM",
    "The Music Locker Underground", "K.U.L.T. 99.1 FM", "Weazel News", "CNT",
}

# Curated, professional UI, menu, HUD, and system phrase glossary
EXACT_PHRASE_GLOSSARY: Dict[str, str] = {
    # System & UI Menus
    "Resume Game": "Lanjutkan Permainan",
    "Resume": "Lanjutkan",
    "Settings": "Pengaturan",
    "Game": "Permainan",
    "Audio": "Audio",
    "Display": "Tampilan",
    "Graphics": "Grafik",
    "Advanced Graphics": "Grafik Lanjutan",
    "Controls": "Kontrol",
    "Key Bindings": "Pintasan Tombol",
    "Keyboard / Mouse": "Papan Ketik / Mouse",
    "Gamepad": "Pengontrol",
    "Camera": "Kamera",
    "Voice Chat": "Obrolan Suara",
    "Notifications": "Pemberitahuan",
    "Saving and Startup": "Penyimpanan dan Memulai",
    "Rockstar Editor": "Editor Rockstar",
    "Brief": "Ringkasan",
    "Help": "Bantuan",
    "Dialog": "Dialog",
    "Log": "Catatan",
    "Stats": "Statistik",
    "Weapons": "Senjata",
    "Skills": "Keahlian",
    "General": "Umum",
    "Vehicles": "Kendaraan",
    "Cash": "Uang",
    "Combat": "Pertempuran",
    "Crimes": "Kejahatan",
    "Overview": "Ikhtisar",
    "Map": "Peta",
    "Friends": "Teman",
    "Info": "Info",
    "Store": "Toko",
    "Quit": "Keluar",
    "Quit Game": "Keluar dari Permainan",
    "Exit": "Keluar",
    "Back": "Kembali",
    "Accept": "Terima",
    "Cancel": "Batal",
    "Select": "Pilih",
    "Confirm": "Konfirmasi",
    "Delete": "Hapus",
    "Apply Changes": "Terapkan Perubahan",
    "Discard Changes": "Buang Perubahan",
    "Default": "Bawaan",
    "Restore Defaults": "Pulihkan Bawaan",
    "On": "Nyala",
    "Off": "Mati",
    "Yes": "Ya",
    "No": "Tidak",
    "None": "Tidak Ada",
    "Low": "Rendah",
    "Normal": "Normal",
    "High": "Tinggi",
    "Very High": "Sangat Tinggi",
    "Ultra": "Ultra",
    "Custom": "Kustom",
    "Auto": "Otomatis",
    "Enabled": "Diaktifkan",
    "Disabled": "Dinonaktifkan",
    "Loading...": "Memuat...",
    "Please wait...": "Harap tunggu...",
    "Saving...": "Menyimpan...",
    "Save Successful": "Penyimpanan Berhasil",
    "Save Failed": "Penyimpanan Gagal",
    "Autosave": "Simpan Otomatis",

    # Minigames & Activities
    "Start Game": "Mulai Permainan",
    "WINNER": "PEMENANG",
    "LOSER": "KALAH",
    "Winner": "Pemenang",
    "Loser": "Kalah",
    "Rematch": "Tanding Ulang",
    "Replay": "Putar Ulang",
    "Result": "Hasil",
    "Opponent": "Lawan",
    "Best Time": "Waktu Terbaik",
    "Checkpoint missed.": "Titik pemeriksaan terlewat.",
    "CHECKPOINT": "TITIK PEMERIKSAAN",
    "1st Place": "Juara 1",
    "2nd Place": "Juara 2",
    "3rd Place": "Juara 3",
    "4th Place": "Peringkat 4",
    "5th Place": "Peringkat 5",
    "6th Place": "Peringkat 6",
    "7th Place": "Peringkat 7",
    "8th Place": "Peringkat 8",
    "SHOT CLOCK": "WAKTU PUKULAN",
    "Shot": "Pukulan",
    "Putt": "Putt",
    "Par": "Par",
    "Aim": "Bidikan",
    "Serve": "Servis",
    "Fault": "Kesalahan",
    "Ace": "Ace",
    "Game, Set, Match": "Game, Set, Pertandingan",

    # Storefront & Inventory
    "FREE": "GRATIS",
    "FULL": "PENUH",
    "ITEMS": "ITEM",
    "Item purchased.": "Item telah dibeli.",
    "Item equipped.": "Item terpasang.",
    "Item owned and equipped.": "Item dimiliki dan terpasang.",
    "Item owned but not equipped.": "Item dimiliki tetapi belum dipasang.",
    "Sorry - you cannot afford this item.": "Maaf - kamu tidak mampu membeli item ini.",
    "Sorry - you already have this item.": "Maaf - kamu sudah memiliki item ini.",
    "Health is already full.": "Kesehatan sudah penuh.",
    "This item is sold out.": "Item ini sudah habis terjual.",
    "This item has just been unlocked.": "Item ini baru saja terbuka.",
    "Snack added to your inventory.": "Camilan ditambahkan ke inventaris kamu.",
    "Shoplift": "Mengutil",
    "CATEGORIES": "KATEGORI",
    "Categories": "Kategori",

    # Clothing & Customization
    "T-Shirts": "Kaos Oblong",
    "T-SHIRTS": "KAOS OBLONG",
    "Sweaters": "Baju Hangat",
    "SWEATERS": "BAJU HANGAT",
    "Pants": "Celana",
    "PANTS": "CELANA",
    "Tank Tops": "Kaos Tanpa Lengan",
    "TANK TOPS": "KAOS TANPA LENGAN",
    "Jackets": "Jaket",
    "JACKETS": "JAKET",
    "Shoes": "Sepatu",
    "SHOES": "SEPATU",
    "Boots": "Sepatu Bot",
    "BOOTS": "SEPATU BOT",
    "Hats": "Topi",
    "HATS": "TOPI",
    "Masks": "Topeng",
    "MASKS": "TOPENG",
    "Glasses": "Kacamata",
    "GLASSES": "KACAMATA",
    "Watches": "Jam Tangan",
    "WATCHES": "JAM TANGAN",
    "Suits": "Jas",
    "SUITS": "JAS",
    "Shirts": "Kemeja",
    "SHIRTS": "KEMEJA",
    "Hoodies": "Hoodie",
    "HOODIES": "HOODIE",
    "Outfits": "Pakaian",
    "OUTFITS": "PAKAIAN",
    "Accessories": "Aksesori",
    "ACCESSORIES": "AKSESORI",
    "Casual": "Santai",
    "Business Casual": "Bisnis Santai",
    "Business": "Bisnis",
    "Formal": "Formal",
    "Sports": "Olahraga",

    # Vehicle Modification / Los Santos Customs
    "WHEELS": "RODA",
    "Wheels": "Roda",
    "DOORS": "PINTU",
    "Doors": "Pintu",
    "TRIM": "TRIM",
    "Trim": "Trim",
    "BUMPERS": "BUMPER",
    "Bumpers": "Bumper",
    "HOODS": "KAP MESIN",
    "Hoods": "Kap Mesin",
    "SPOILERS": "SPOILER",
    "Spoilers": "Spoiler",
    "EXHAUSTS": "KNALPOT",
    "Exhausts": "Knalpot",
    "LIGHTS": "LAMPU",
    "Lights": "Lampu",
    "ENGINE": "MESIN",
    "Engine": "Mesin",
    "BRAKES": "REM",
    "Brakes": "Rem",
    "TRANSMISSION": "TRANSMISI",
    "Transmission": "Transmisi",
    "SUSPENSION": "SUSPENSI",
    "Suspension": "Suspensi",
    "TURBO": "TURBO",
    "Turbo": "Turbo",
    "WINDOWS": "KACA",
    "Windows": "Kaca",
    "RESPRAY": "CAT ULANG",
    "Respray": "Cat Ulang",
    "PRIMARY COLOR": "WARNA UTAMA",
    "SECONDARY COLOR": "WARNA KEDUA",
    "PEARLESCENT": "MUTIARA",
    "METALLIC": "METALIK",
    "MATTE": "DOFF",
    "CLASSIC": "KLASIK",
    "METALS": "LOGAM",
    "CHROME": "KROM",
    "Armor Upgrade 20%": "Peningkatan Pelindung 20%",
    "Armor Upgrade 40%": "Peningkatan Pelindung 40%",
    "Armor Upgrade 60%": "Peningkatan Pelindung 60%",
    "Armor Upgrade 80%": "Peningkatan Pelindung 80%",
    "Armor Upgrade 100%": "Peningkatan Pelindung 100%",

    # Weapons & Ammu-Nation
    "ARMORY": "PERSENJATAAN",
    "PISTOLS": "PISTOL",
    "Pistols": "Pistol",
    "EXPLOSIVES": "BAHAN PELEDAK",
    "Explosives": "Bahan Peledak",
    "HEAVY WEAPONS": "SENJATA BERAT",
    "Heavy Weapons": "Senjata Berat",
    "THROWABLES": "SENJATA LEMPAR",
    "Throwables": "Senjata Lempar",
    "BODY ARMOR": "ROMPI ANTI PELURU",
    "ARMOR": "ROMPI",
    "Armor": "Rompi",
    "MACHINE GUNS": "SENJATA MESIN",
    "Machine Guns": "Senjata Mesin",
    "SNIPER RIFLES": "SENAPAN PENEMBAK JITU",
    "Sniper Rifles": "Senapan Penembak Jitu",
    "MELEE WEAPONS": "SENJATA JARAK DEKAT",
    "Melee Weapons": "Senjata Jarak Dekat",
    "Parachutes": "Parasut",
    "EQUIPPED": "TERPASANG",
    "UPGRADE": "TINGKATKAN",
    "Upgrade": "Tingkatkan",
    "Charge": "Peledak",
    "Round": "Peluru",
    "Grenade": "Granat",
    "Rocket": "Roket",
    "Default Weapon": "Senjata Bawaan",
    "Default Component": "Komponen Bawaan",
    "Purchase Weapon Ammo.": "Beli Amunisi Senjata.",
    "GUN VAN": "VAN SENJATA",
    "REQUISITIONS OFFICER": "PETUGAS LOGISTIK",

    # Phone & Communication
    "Inbox": "Kotak Masuk",
    "Pick a response": "Pilih tanggapan",
    "Contacts": "Kontak",
    "Messages": "Pesan",
    "Emails": "Email",
    "Photos": "Foto",
    "Job List": "Daftar Pekerjaan",
    "Quick Save": "Simpan Cepat",

    # Mission Outcomes & Status
    "Mission Passed": "Misi Berhasil",
    "MISSION PASSED": "MISI BERHASIL",
    "Mission Failed": "Misi Gagal",
    "Passed": "Berhasil",
    "Failed": "Gagal",
    "FAILED": "GAGAL",
    "Bronze": "Perunggu",
    "Silver": "Perak",
    "Gold": "Emas",
    "Total": "Total",
    "Checklist": "Daftar Sasaran",
    "Objective": "Tujuan",
    "Objectives": "Tujuan",
    "Accuracy": "Akurasi",
    "Time": "Waktu",
    "Headshots": "Tembakan Kepala",
    "Damage": "Kerusakan",
    "Restart": "Mulai Ulang",
    "Retry": "Coba Lagi",
    "Continue": "Lanjutkan",
    "Skip": "Lewati",
    "Skip Trip": "Lewati Perjalanan",

    # Wanted & Cops
    "Lose the cops.": "Lolos dari kejaran polisi.",
    "Lose the cops": "Lolos dari kejaran polisi",
    "Lose the Cops.": "Lolos dari kejaran Polisi.",
    "Lose the Cops": "Lolos dari kejaran Polisi",
    "Lose your Wanted Level.": "Hilangkan Status Buronanmu.",
    "Lose your Wanted Level": "Hilangkan Status Buronanmu",
    "Wanted Level": "Status Buronan",
    "WANTED": "BURONAN",
    "BUSTED": "TERTANGKAP",
    "WASTED": "TEWAS",
    "DEAD": "TEWAS",
    "KIA!": "TEWAS!",
    "The Cops were alerted.": "Polisi disiagakan.",

    # Heist & Casualties
    "The crew was abandoned.": "Kru ditinggalkan.",
    "The crew were left behind.": "Kru tertinggal di belakang.",
    "The heist was abandoned.": "Perampokan dibatalkan.",
    "One of the crew members died.": "Salah satu anggota kru tewas.",
    "The crew members died.": "Anggota kru tewas.",
    "A crew member was abandoned.": "Seorang anggota kru ditinggalkan.",
    "Franklin died.": "Franklin tewas.",
    "Michael died.": "Michael tewas.",
    "Trevor died.": "Trevor tewas.",
    "Lester died.": "Lester tewas.",
    "Lamar died.": "Lamar tewas.",
    "Brad died.": "Brad tewas.",
    "Wade died.": "Wade tewas.",
    "Wade was abandoned.": "Wade ditinggalkan.",
    "Dom died.": "Dom tewas.",
    "Dom was spooked.": "Dom ketakutan.",
    "Beverly died.": "Beverly tewas.",
    "Beverly was spooked.": "Beverly ketakutan.",
    "Kill Beverly or let him go.": "Habisi Beverly atau biarkan dia pergi.",
    "Mary-Ann died.": "Mary-Ann tewas.",
    "Mary-Ann got too far ahead.": "Mary-Ann melaju terlalu jauh di depan.",
    "Jimmy died.": "Jimmy tewas.",
    "Jimmy was abandoned.": "Jimmy ditinggalkan.",
    "Tracey died.": "Tracey tewas.",
    "Chop died.": "Chop mati.",
    "The driver died.": "Pengemudi tewas.",
    "The car was abandoned.": "Mobil ditinggalkan.",
    "The car was destroyed.": "Mobil hancur.",
    "The cars were destroyed.": "Mobil-mobil hancur.",
    "The vehicle was destroyed.": "Kendaraan hancur.",
    "One of the cars was destroyed.": "Salah satu mobil hancur.",
    "Some of the cars were destroyed.": "Beberapa mobil hancur.",
    "The truck was destroyed.": "Truk hancur.",
    "The van was destroyed.": "Mobil van hancur.",
    "The car is stuck.": "Mobil tersangkut.",
    "The car got stuck.": "Mobil tersangkut.",
    "The car was stuck in the snow.": "Mobil terjebak di dalam salju.",
    "The race was lost.": "Balapan kalah.",
    "The race was abandoned.": "Balapan dibatalkan.",
    "Out of ammo.": "Kehabisan amunisi.",
    "The hostage got away.": "Sandera melarikan diri.",
    "A hostage died.": "Seorang sandera tewas.",
    "M. died.": "M. tewas.",
    "T. died.": "T. tewas.",
    "Franklin was abandoned.": "Franklin ditinggalkan.",
    "Michael was abandoned.": "Michael ditinggalkan.",
    "Lamar was abandoned.": "Lamar ditinggalkan.",
    "Don't leave Michael behind.": "Jangan tinggalkan Michael.",
    "Don't leave Trevor behind.": "Jangan tinggalkan Trevor.",
    "Don't leave Franklin behind.": "Jangan tinggalkan Franklin.",
    "Take out the attackers.": "Lumpuhkan para penyerang.",
    "Take out the guards.": "Lumpuhkan para penjaga.",
    "Return to Franklin.": "Kembalilah ke Franklin.",
    "Return to Lamar.": "Kembalilah ke Lamar.",
    "Return to Trevor.": "Kembalilah ke Trevor.",
    "Return to Michael.": "Kembalilah ke Michael.",
    "Return to the crew.": "Kembalilah ke kru.",
    "Follow Lamar.": "Ikuti Lamar.",
    "Wait for Dom.": "Tunggu Dom.",
    "Get back in the truck.": "Masuklah kembali ke truk.",
    "Get in the truck.": "Masuklah ke dalam truk.",
    "Get into the car.": "Masuklah ke dalam mobil.",
    "Get back into the car.": "Masuklah kembali ke dalam mobil.",
    "Get back in the car.": "Masuklah kembali ke dalam mobil.",
    "Get in the car.": "Masuklah ke dalam mobil.",
    "Get in the van.": "Masuklah ke dalam mobil van.",
    "Get back in the van.": "Masuklah kembali ke mobil van.",
    "Get back on the bike.": "Naiklah kembali ke motor.",
    "Get back on the Seashark.": "Naiklah kembali ke Seashark.",
    "Go back to Michael's house.": "Kembalilah ke rumah Michael.",
    "Go to the strip club.": "Pergilah ke klub tari telanjang.",
    "Go to the house.": "Pergilah ke rumah.",
    "Leave the vehicle.": "Tinggalkan kendaraan.",
    "Pick up a container.": "Ambil kontainer.",
    "Shoot the gasoline trail to ignite it.": "Tembak jejak bensin untuk menyulutnya.",

    # Authentic Dialogue & Expletives (Uncensored, Natural Indonesian)
    "Shut the fuck up!": "Tutup mulutmu, bangsat!",
    "Shut up!": "Diam!",
    "Get the fuck out!": "Keluar dari sini, bangsat!",
    "Come on!": "Ayo!",
    "Come on.": "Ayo.",
    "What the fuck?": "Apa-apaan nih?",
    "What the hell are you doing?": "Ngapain sih kamu?",
    "Are you crazy?": "Kamu gila ya?",
    "Get down!": "Tiarap!",
    "Get down on the ground!": "Tiarap ke tanah!",
    "Get down there!": "Turun ke sana!",
    "Alright, everybody pays attention, no one gets hurt.": "Baiklah, perhatikan semuanya, tidak ada yang akan terluka.",
    "Aarrgh! Open the door, or they'll get worse than hurt!": "Aarrgh! Buka pintunya, atau mereka akan mengalami yang lebih buruk dari sekadar luka!",
    "Hey, hey, ah! Come on!": "Hei, hei, ah! Ayo!",
    "Ludendorff, North Yankton, nine years ago.": "Ludendorff, North Yankton, sembilan tahun yang lalu.",
    "Take cover.": "Berlindunglah.",
    "Take cover": "Berlindung",
    "Leave the area.": "Tinggalkan area ini.",
    "Leave the area": "Tinggalkan area",
    "Escape": "Kabur",
    "Get to safety.": "Pergilah ke tempat aman.",
    "Enter the vehicle.": "Masuk ke dalam kendaraan.",
    "Exit the vehicle.": "Keluar dari kendaraan.",
    "Steal the vehicle.": "Curi kendaraan tersebut.",
    "Plant the explosives.": "Pasang bahan peledak.",
    "Detonate the explosives.": "Ledakkan bahan peledak.",
    "Detonate": "Ledakkan",
    "Open the vault.": "Buka brankasnya.",

    # News Headlines
    "Finally! Los Santos is getting a football team.": "Akhirnya! Los Santos mendapatkan tim sepak bola.",
    "Data thieves raid Bureau, Helicopter crash devastates building.": "Pencuri data serang Biro, Helikopter jatuh luluhlantakkan gedung.",
    "Begging goes cyber with Beseecher.": "Mengemis merambah dunia maya lewat Beseecher.",
    "Possible breakthrough in Leonora Johnson case.": "Kemungkinan titik terang dalam kasus Leonora Johnson.",
    "Several dead in suspected gang shoot-out.": "Sejumlah orang tewas dalam baku tembak antar geng.",
    "Paps smear.": "Paparazi berulah.",
    "Gang wars, gun smuggling terrorize region.": "Perang geng dan penyelundupan senjata teror wilayah.",
    "Lifeinvader to revolutionize with new product.": "Lifeinvader siap guncang pasar dengan produk baru.",
    "Rash of ATM robberies.": "Marak aksi perampokan ATM.",
    "Big Brother in your bathroom?": "Mata-mata di dalam kamar mandimu?",
}

# Regex patterns for mission directives, tutorials, radar blips, and character switching
MISSION_DIRECTIVE_PATTERNS: List[Tuple[str, str]] = [
    # Character Switching
    (r"^SWITCH to Franklin\.$", r"BERALIH ke Franklin."),
    (r"^SWITCH to Trevor\.$", r"BERALIH ke Trevor."),
    (r"^SWITCH to Michael\.$", r"BERALIH ke Michael."),
    (r"^SWITCH to Michael to drive\.$", r"BERALIH ke Michael untuk menyetir."),
    (r"^You can SWITCH between playable characters\.$", r"Kamu dapat BERALIH di antara karakter yang dapat dimainkan."),
    (r"^The flashing face icon shows who to SWITCH to\.$", r"Ikon wajah yang berkedip menunjukkan siapa karakter tujuan untuk BERALIH."),
    (r"^Use SWITCH to gain control of (~[byr]~[^~]+~s~)\.$", r"Gunakan SWITCH untuk mengambil kendali atas \1."),
    (r"^Use SWITCH to gain control of your crew member\.$", r"Gunakan SWITCH untuk mengambil kendali atas anggota krumu."),
    (r"^To SWITCH hold (~INPUT[^~]+~) to show the available characters\.$", r"Untuk BERALIH tahan \1 untuk menampilkan karakter yang tersedia."),
    (r"^While holding (~INPUT[^~]+~) use (~INPUTGROUP_WHEEL~) to select a character, then release (~INPUT_CHARACTER_WHEEL~) to SWITCH\.$", r"Sambil menahan \1 gunakan \2 untuk memilih karakter, lalu lepaskan \3 untuk BERALIH."),
    (r"^Quick SWITCH to the most relevant character by tapping (~INPUT[^~]+~)$", r"BERALIH cepat ke karakter yang paling relevan dengan mengetuk \1"),

    # Navigation / Movement
    (r"^Go to the (~y~[^~]+~s~)\.?$", r"Pergilah ke \1."),
    (r"^Go to the (~y~[^~]+~s~) room\.?$", r"Pergilah ke ruang \1."),
    (r"^Go to (~[byr]~[^~]+~s~)\.?$", r"Pergilah ke \1."),
    (r"^Wait for (~[byr]~[^~]+~s~) to get to the car\.?$", r"Tunggu \1 sampai di mobil."),
    (r"^Wait for (~[byr]~[^~]+~s~) to get in the car\.?$", r"Tunggu \1 masuk ke dalam mobil."),
    (r"^Wait for the (~[byr]~[^~]+~s~) to get in the car\.?$", r"Tunggu \1 masuk ke dalam mobil."),
    (r"^Wait for the (~[byr]~[^~]+~s~)\.?$", r"Tunggu \1."),
    (r"^Wait for (~[byr]~[^~]+~s~)\.?$", r"Tunggu \1."),
    (r"^Follow (~[byr]~[^~]+~s~)\.?$", r"Ikuti \1."),
    (r"^Return to the (~[byr]~[^~]+~s~)\.?$", r"Kembalilah ke \1."),
    (r"^Return to (~[byr]~[^~]+~s~)\.?$", r"Kembalilah ke \1."),
    (r"^Return to your (~[byr]~[^~]+~s~)\.?$", r"Kembalilah ke \1mu."),
    (r"^Get in the car\.?$", r"Masuklah ke dalam mobil."),
    (r"^Get back in the (~[byr]~[^~]+~s~)\.?$", r"Masuklah kembali ke dalam \1."),
    (r"^Get to the (~[byr]~[^~]+~s~)\.?$", r"Capailah \1."),
    (r"^Get to (~y~[^~]+~s~)\.?$", r"Pergilah ke \1."),
    (r"^Drive to the (~y~[^~]+~s~)\.?$", r"Berkendaralah ke \1."),

    # Combat & Action Directives
    (r"^Grab the (~[byr]~[^~]+~s~)\.?$", r"Tangkap \1."),
    (r"^Shoot the (~[byr]~[^~]+~s~)\.?$", r"Tembak \1."),
    (r"^Aim at the (~[byr]~[^~]+~s~) to make them move\.?$", r"Bidik \1 agar mereka bergerak."),
    (r"^Take out the (~[byr]~[^~]+~s~)\.?$", r"Lumpuhkan \1."),
    (r"^Quietly take out the (~[byr]~[^~]+~s~)\.?$", r"Lumpuhkan \1 secara diam-diam."),
    (r"^Escape the (~[byr]~[^~]+~s~)\.?$", r"Loloslah dari \1."),
    (r"^Hold off the (~[byr]~[^~]+~s~)\.?$", r"Tahan serangan \1."),
    (r"^Open the (~[byr]~[^~]+~s~)\.?$", r"Bukalah \1."),
    (r"^Collect the (~[byr]~[^~]+~s~)\.?$", r"Ambil \1."),
    (r"^Collect (~[byr]~[^~]+~s~)\.?$", r"Kumpulkan \1."),
    (r"^Protect (~[byr]~[^~]+~s~)\.?$", r"Lindungi \1."),
    (r"^Take (~y~cover~s~) by the Cop cars\.?$", r"Ambillah \1 di dekat mobil Polisi."),
    (r"^Stay in the (~y~[^~]+~s~) and watch over the hostages\.?$", r"Tetaplah di \1 dan awasi para sandera."),
    (r"^Stay in the (~y~[^~]+~s~) to safely detonate the explosives\.?$", r"Tetaplah di \1 untuk meledakkan bahan peledak dengan aman."),
    (r"^Use the phone to trigger the explosive charge\.?$", r"Gunakan ponsel untuk memicu muatan peledak."),

    # Radar Blips
    (
        r"^(~r~Enemies~s~|~r~Musuh~s~) are marked with a (~HUD_COLOUR_RED~~BLIP_OBJECTIVE~~s~) on the Radar\.$",
        r"~r~Musuh~s~ ditandai dengan \2 di Radar.",
    ),
    (
        r"^(~b~Friends~s~|~b~Teman~s~) are marked with a (~HUD_COLOUR_BLUE~~BLIP_OBJECTIVE~~s~) on the Radar\.$",
        r"~b~Kawan~s~ ditandai dengan \2 di Radar.",
    ),
    (
        r"^(~g~Objects~s~|~g~Objek~s~) are marked with a (~HUD_COLOUR_GREEN~~BLIP_OBJECTIVE~~s~) on the Radar\.$",
        r"~g~Objek~s~ ditandai dengan \2 di Radar.",
    ),
    (
        r"^(~y~Locations~s~|~y~Lokasi~s~) are marked with a (~HUD_COLOUR_YELLOW~~BLIP_OBJECTIVE~~s~) on the Radar\.$",
        r"~y~Lokasi~s~ ditandai dengan \2 di Radar.",
    ),
    (
        r"^Your (~y~destination~s~) is marked with a (~HUD_COLOUR_YELLOW~~BLIP_OBJECTIVE~~s~) on the Radar\.$",
        r"\1mu ditandai dengan \2 di Radar.",
    ),
    (
        r"^The Radar shows your position within the world\.$",
        r"Radar menunjukkan posisimu di dalam dunia permainan.",
    ),
    (
        r"^GPS indicates the shortest legal route to a destination with a yellow line\.$",
        r"GPS menunjukkan rute resmi terpendek menuju tujuan dengan garis kuning.",
    ),

    # Controls & Tutorial Inputs
    (r"^Press (~INPUT[^~]+~) to toggle focus on ([A-Za-z0-9_]+)\.$", r"Tekan \1 untuk beralih fokus ke \2."),
    (r"^Press (~INPUT[^~]+~) to toggle focus on the target\.$", r"Tekan \1 untuk beralih fokus ke target."),
    (r"^Press (~INPUT[^~]+~) to toggle cinematic camera\.$", r"Tekan \1 untuk beralih ke kamera sinematik."),
    (r"^Press (~INPUT[^~]+~) to freely SWITCH between Michael and Trevor\.$", r"Tekan \1 untuk BERALIH bebas antara Michael dan Trevor."),
    (r"^Press (~INPUT[^~]+~) to access the menu\.$", r"Tekan \1 untuk membuka menu."),
    (r"^Press (~INPUT[^~]+~) to exit the phone menu and put away the phone\.$", r"Tekan \1 untuk keluar dari menu ponsel dan menyimpan ponsel."),
    (r"^Press (~INPUT[^~]+~) to get in a vehicle\.$", r"Tekan \1 untuk masuk ke dalam kendaraan."),
    (r"^Press (~INPUT[^~]+~) to take cover\.$", r"Tekan \1 untuk berlindung."),
    (r"^Press (~INPUT[^~]+~) again to leave cover\. You can also move away from cover using (~INPUTGROUP_MOVE~)\.$", r"Tekan \1 lagi untuk keluar dari perlindungan. Kamu juga bisa bergerak menjauh dari perlindungan menggunakan \2."),
    (r"^Press (~INPUT[^~]+~) to shoot\.$", r"Tekan \1 untuk menembak."),
    (r"^Press (~INPUT[^~]+~) to reload a weapon\.$", r"Tekan \1 untuk mengisi ulang senjata."),
    (r"^Press (~INPUT[^~]+~) without aiming to run and gun\.$", r"Tekan \1 tanpa membidik untuk menembak sambil berlari."),
    (r"^Press (~INPUT[^~]+~) to toggle run/walk\.$", r"Tekan \1 untuk beralih antara lari/jalan."),
    (r"^Press (~INPUT[^~]+~) to bring up the phone\.$", r"Tekan \1 untuk membuka ponsel."),
    (r"^Press (~INPUT[^~]+~) to view the contact list\.$", r"Tekan \1 untuk melihat daftar kontak."),
    (r"^Press (~INPUT[^~]+~) to activate Franklin's special ability\.$", r"Tekan \1 untuk mengaktifkan kemampuan khusus Franklin."),
    (r"^With \"Detonate\" highlighted press (~INPUT[^~]+~) to call\.$", r"Dengan memilih \"Ledakkan\", tekan \1 untuk menelepon."),
    (r"^Tap (~INPUT[^~]+~) to sprint when outside\.$", r"Ketuk \1 untuk berlari cepat saat berada di luar."),
    (r"^Hold (~INPUT[^~]+~) to run and (~INPUT_SPRINT~) to sprint when outside\.$", r"Tahan \1 untuk berlari dan \2 untuk berlari cepat saat berada di luar."),
    (r"^Hold (~INPUT[^~]+~) to sprint when outside\.$", r"Tahan \1 untuk berlari cepat saat berada di luar."),
    (r"^Hold (~INPUT[^~]+~) to run\.$", r"Tahan \1 untuk berlari."),
    (r"^Hold (~INPUT[^~]+~) to accelerate\.$", r"Tahan \1 untuk menambah kecepatan."),
    (r"^Hold (~INPUT[^~]+~) to brake or reverse if the vehicle is stopped\.$", r"Tahan \1 untuk mengerem atau mundur saat kendaraan berhenti."),
    (r"^Hold (~INPUT[^~]+~) and guide the gunfire with (~INPUTGROUP_LOOK~)$", r"Tahan \1 dan arahkan tembakan dengan \2"),
    (r"^Use (~INPUT[^~]+~) to steer a vehicle\.$", r"Gunakan \1 untuk mengemudikan kendaraan."),
    (r"^Use (~INPUT[^~]+~) to navigate the phone menu\.$", r"Gunakan \1 untuk menavigasi menu ponsel."),
    (r"^Use (~INPUT[^~]+~) to aim and lock-on\.$", r"Gunakan \1 untuk membidik dan mengunci target."),
    (r"^Use (~INPUT[^~]+~) to aim at a target\.$", r"Gunakan \1 untuk membidik target."),
    (r"^Use (~INPUT[^~]+~) to aim at enemies while in cover, then shoot with (~INPUT_ATTACK~)$", r"Gunakan \1 untuk membidik musuh saat berlindung, lalu tembak dengan \2"),
    (r"^Use (~INPUT[^~]+~) to aim\.$", r"Gunakan \1 untuk membidik."),
    (r"^Use (~INPUT[^~]+~) to walk\.$", r"Gunakan \1 untuk berjalan."),
    (r"^Use (~INPUT[^~]+~) to hurry the hostages\.$", r"Gunakan \1 untuk mempercepat para sandera."),
    (r"^Use (~INPUT[^~]+~) to zoom in while aiming\.$", r"Gunakan \1 untuk memperbesar bidikan."),
    (r"^Aim at the guard using (~INPUT[^~]+~)$", r"Bidik penjaga menggunakan \1"),
    (r"^Aim using (~INPUT[^~]+~)$", r"Bidik menggunakan \1"),
    (r"^While locked on, use (~INPUTGROUP_LOOK~) to switch between targets\.$", r"Saat terkunci, gunakan \1 untuk beralih di antara target."),
    (r"^While aiming, use (~INPUTGROUP_LOOK~) to target the hostages\.$", r"Saat membidik, gunakan \1 untuk mengarahkan ke para sandera."),
    (r"^While locked on you can flick between targets with (~INPUTGROUP_LOOK~)$", r"Saat terkunci kamu dapat berpindah antar target dengan \1"),
    (r"^Free aim by half pressing (~INPUT[^~]+~)$", r"Bidikan bebas dengan menekan setengah \1"),
    (r"^As a passenger press (~INPUT[^~]+~) to aim and (~INPUT_VEH_PASSENGER_ATTACK~) to shoot from a vehicle\.$", r"Sebagai penumpang tekan \1 untuk membidik dan \2 untuk menembak dari kendaraan."),
    (r"^While not aiming, press (~INPUT[^~]+~) to shoot at enemies or targets and guide the gunfire with (~INPUTGROUP_LOOK~)$", r"Saat tidak membidik, tekan \1 untuk menembak musuh atau target dan arahkan tembakan dengan \2"),
]
